repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
        files: ^backend/
      - id: ruff-format
        files: ^backend/
