"""add ondelete cascade and fk indexes

Revision ID: a7d2c52d0232
Revises: 7092c08bdc28
Create Date: 2026-08-06 15:39:59.626338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d2c52d0232'
down_revision: Union[str, Sequence[str], None] = '7092c08bdc28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_favourite_team_id'), 'favourite', ['team_id'], unique=False)
    op.drop_constraint(op.f('favourite_team_id_fkey'), 'favourite', type_='foreignkey')
    op.create_foreign_key(None, 'favourite', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_file_favourite_id'), 'file', ['favourite_id'], unique=False)
    op.create_index(op.f('ix_file_note_id'), 'file', ['note_id'], unique=False)
    op.drop_constraint(op.f('file_favourite_id_fkey'), 'file', type_='foreignkey')
    op.drop_constraint(op.f('file_note_id_fkey'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'favourite', ['favourite_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'file', 'note', ['note_id'], ['id'], ondelete='CASCADE')
    op.add_column('like_user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('like_user', sa.Column('favourite_id', sa.Integer(), nullable=False))
    op.create_index('ix_like_user_favourite_id', 'like_user', ['favourite_id'], unique=False)
    op.drop_constraint(op.f('like_user_favourites_id_fkey'), 'like_user', type_='foreignkey')
    op.drop_constraint(op.f('like_user_users_id_fkey'), 'like_user', type_='foreignkey')
    op.create_foreign_key(None, 'like_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'like_user', 'favourite', ['favourite_id'], ['id'], ondelete='CASCADE')
    op.drop_column('like_user', 'users_id')
    op.drop_column('like_user', 'favourites_id')
    op.create_index(op.f('ix_note_team_id'), 'note', ['team_id'], unique=False)
    op.drop_constraint(op.f('note_team_id_fkey'), 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_route_team_id'), 'route', ['team_id'], unique=False)
    op.drop_constraint(op.f('route_team_id_fkey'), 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.add_column('tag_favourite', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.add_column('tag_favourite', sa.Column('favourite_id', sa.Integer(), nullable=False))
    op.create_index('ix_tag_favourite_favourite_id', 'tag_favourite', ['favourite_id'], unique=False)
    op.drop_constraint(op.f('tag_favourite_tags_id_fkey'), 'tag_favourite', type_='foreignkey')
    op.drop_constraint(op.f('tag_favourite_favourites_id_fkey'), 'tag_favourite', type_='foreignkey')
    op.create_foreign_key(None, 'tag_favourite', 'favourite', ['favourite_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tag_favourite', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tag_favourite', 'tags_id')
    op.drop_column('tag_favourite', 'favourites_id')
    op.add_column('tag_note', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.add_column('tag_note', sa.Column('note_id', sa.Integer(), nullable=False))
    op.create_index('ix_tag_note_note_id', 'tag_note', ['note_id'], unique=False)
    op.drop_constraint(op.f('tag_note_tags_id_fkey'), 'tag_note', type_='foreignkey')
    op.drop_constraint(op.f('tag_note_notes_id_fkey'), 'tag_note', type_='foreignkey')
    op.create_foreign_key(None, 'tag_note', 'note', ['note_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tag_note', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tag_note', 'tags_id')
    op.drop_column('tag_note', 'notes_id')
    op.add_column('tag_route', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.add_column('tag_route', sa.Column('route_id', sa.Integer(), nullable=False))
    op.create_index('ix_tag_route_route_id', 'tag_route', ['route_id'], unique=False)
    op.drop_constraint(op.f('tag_route_routes_id_fkey'), 'tag_route', type_='foreignkey')
    op.drop_constraint(op.f('tag_route_tags_id_fkey'), 'tag_route', type_='foreignkey')
    op.create_foreign_key(None, 'tag_route', 'route', ['route_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tag_route', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tag_route', 'tags_id')
    op.drop_column('tag_route', 'routes_id')
    op.add_column('user_team', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user_team', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_index('ix_user_team_team_id', 'user_team', ['team_id'], unique=False)
    op.drop_constraint(op.f('user_team_teams_id_fkey'), 'user_team', type_='foreignkey')
    op.drop_constraint(op.f('user_team_users_id_fkey'), 'user_team', type_='foreignkey')
    op.create_foreign_key(None, 'user_team', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_team', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_team', 'users_id')
    op.drop_column('user_team', 'teams_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_team', sa.Column('teams_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_team', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_team', type_='foreignkey')
    op.drop_constraint(None, 'user_team', type_='foreignkey')
    op.create_foreign_key(op.f('user_team_users_id_fkey'), 'user_team', 'user', ['users_id'], ['id'])
    op.create_foreign_key(op.f('user_team_teams_id_fkey'), 'user_team', 'team', ['teams_id'], ['id'])
    op.drop_index('ix_user_team_team_id', table_name='user_team')
    op.drop_column('user_team', 'team_id')
    op.drop_column('user_team', 'user_id')
    op.add_column('tag_route', sa.Column('routes_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tag_route', sa.Column('tags_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tag_route', type_='foreignkey')
    op.drop_constraint(None, 'tag_route', type_='foreignkey')
    op.create_foreign_key(op.f('tag_route_tags_id_fkey'), 'tag_route', 'tag', ['tags_id'], ['id'])
    op.create_foreign_key(op.f('tag_route_routes_id_fkey'), 'tag_route', 'route', ['routes_id'], ['id'])
    op.drop_index('ix_tag_route_route_id', table_name='tag_route')
    op.drop_column('tag_route', 'route_id')
    op.drop_column('tag_route', 'tag_id')
    op.add_column('tag_note', sa.Column('notes_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tag_note', sa.Column('tags_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tag_note', type_='foreignkey')
    op.drop_constraint(None, 'tag_note', type_='foreignkey')
    op.create_foreign_key(op.f('tag_note_notes_id_fkey'), 'tag_note', 'note', ['notes_id'], ['id'])
    op.create_foreign_key(op.f('tag_note_tags_id_fkey'), 'tag_note', 'tag', ['tags_id'], ['id'])
    op.drop_index('ix_tag_note_note_id', table_name='tag_note')
    op.drop_column('tag_note', 'note_id')
    op.drop_column('tag_note', 'tag_id')
    op.add_column('tag_favourite', sa.Column('favourites_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tag_favourite', sa.Column('tags_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tag_favourite', type_='foreignkey')
    op.drop_constraint(None, 'tag_favourite', type_='foreignkey')
    op.create_foreign_key(op.f('tag_favourite_favourites_id_fkey'), 'tag_favourite', 'favourite', ['favourites_id'], ['id'])
    op.create_foreign_key(op.f('tag_favourite_tags_id_fkey'), 'tag_favourite', 'tag', ['tags_id'], ['id'])
    op.drop_index('ix_tag_favourite_favourite_id', table_name='tag_favourite')
    op.drop_column('tag_favourite', 'favourite_id')
    op.drop_column('tag_favourite', 'tag_id')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key(op.f('route_team_id_fkey'), 'route', 'team', ['team_id'], ['id'])
    op.drop_index(op.f('ix_route_team_id'), table_name='route')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key(op.f('note_team_id_fkey'), 'note', 'team', ['team_id'], ['id'])
    op.drop_index(op.f('ix_note_team_id'), table_name='note')
    op.add_column('like_user', sa.Column('favourites_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('like_user', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'like_user', type_='foreignkey')
    op.drop_constraint(None, 'like_user', type_='foreignkey')
    op.create_foreign_key(op.f('like_user_users_id_fkey'), 'like_user', 'user', ['users_id'], ['id'])
    op.create_foreign_key(op.f('like_user_favourites_id_fkey'), 'like_user', 'favourite', ['favourites_id'], ['id'])
    op.drop_index('ix_like_user_favourite_id', table_name='like_user')
    op.drop_column('like_user', 'favourite_id')
    op.drop_column('like_user', 'user_id')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_note_id_fkey'), 'file', 'note', ['note_id'], ['id'])
    op.create_foreign_key(op.f('file_favourite_id_fkey'), 'file', 'favourite', ['favourite_id'], ['id'])
    op.drop_index(op.f('ix_file_note_id'), table_name='file')
    op.drop_index(op.f('ix_file_favourite_id'), table_name='file')
    op.drop_constraint(None, 'favourite', type_='foreignkey')
    op.create_foreign_key(op.f('favourite_team_id_fkey'), 'favourite', 'team', ['team_id'], ['id'])
    op.drop_index(op.f('ix_favourite_team_id'), table_name='favourite')
    # ### end Alembic commands ###
