"""create_tables

Revision ID: 7092c08bdc28
Revises:
Create Date: 2026-08-05 12:03:36.141753

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7092c08bdc28"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_login"), "user", ["login"], unique=True)
    op.create_table(
        "favourite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "route",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_team",
        sa.Column("users_id", sa.Integer(), nullable=False),
        sa.Column("teams_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["teams_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("users_id", "teams_id"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("minio_id", sa.String(length=255), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=True),
        sa.Column("favourite_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["favourite_id"],
            ["favourite.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("minio_id"),
    )
    op.create_table(
        "like_user",
        sa.Column("users_id", sa.Integer(), nullable=False),
        sa.Column("favourites_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["favourites_id"],
            ["favourite.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("users_id", "favourites_id"),
    )
    op.create_table(
        "tag_favourite",
        sa.Column("tags_id", sa.Integer(), nullable=False),
        sa.Column("favourites_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["favourites_id"],
            ["favourite.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tags_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("tags_id", "favourites_id"),
    )
    op.create_table(
        "tag_note",
        sa.Column("tags_id", sa.Integer(), nullable=False),
        sa.Column("notes_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["notes_id"],
            ["note.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tags_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("tags_id", "notes_id"),
    )
    op.create_table(
        "tag_route",
        sa.Column("tags_id", sa.Integer(), nullable=False),
        sa.Column("routes_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["routes_id"],
            ["route.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tags_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("tags_id", "routes_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag_route")
    op.drop_table("tag_note")
    op.drop_table("tag_favourite")
    op.drop_table("like_user")
    op.drop_table("file")
    op.drop_table("user_team")
    op.drop_table("route")
    op.drop_table("note")
    op.drop_table("favourite")
    op.drop_index(op.f("ix_user_login"), table_name="user")
    op.drop_table("user")
    op.drop_table("team")
    op.drop_table("tag")
    # ### end Alembic commands ###
